# Generated by Django 5.2.7 on 2025-10-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='weeks',
            field=models.PositiveIntegerField(default=52, help_text='Número de semanas del contrato'),
        ),
    ]
