# Generated by Django 5.2.7 on 2025-10-20 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('clients', '0001_initial'),
        ('contracts', '0003_contract_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='weeks',
            field=models.PositiveIntegerField(default=52),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client',), name='unique_active_contract_per_client'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('car',), name='unique_active_contract_per_car'),
        ),
    ]
