# Generated by Django 5.2.7 on 2025-10-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_options_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['created_at']},
        ),
    ]
